on:
  push:
    branches:    
      - 'live'
name: 🚀 Deploy Live website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: hestia.engelbrecht.pro
        username: SpyMiner_live
        password: Password
